import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const InterFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${InterFont.variable} antialiased min-h-screen overflow-x-hidden bg-neutral-950 text-neutral-300 selection:bg-red-500/30 selection:text-red-200`}
      >
        <div className="fixed inset-0 z-0 pointer-events-none">
          <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full h-[80vh] bg-[radial-gradient(ellipse_at_top,var(--tw-gradient-stops))] from-neutral-800/30 via-neutral-950/80 to-transparent opacity-60"></div>
        </div>
        {children}
      </body>
    </html>
  );
}
