export const IDEA_CATEGORIES = [
  "Technology",
  "Programming",
  "Artificial Intelligence",
  "Robotics",
  "Electronics",
  "Web Development",
  "Mobile Apps",
  "Game Development",
  "Cybersecurity",
  "Data Science",
  "Science",
  "Astronomy",
  "Physics",
  "Chemistry",
  "Biology",
  "Mathematics",
  "Engineering",
  "Space Exploration",
  "Environmental Science",
  "Experiments",
  "Art",
  "Drawing",
  "Painting",
  "Sculpture",
  "Photography",
  "Graphic Design",
  "Animation",
  "Illustration",
  "Calligraphy",
  "Digital Art",
  "Music",
  "Singing",
  "Songwriting",
  "Musical Instruments",
  "Dance",
  "Theater",
  "Film",
  "Creative Writing",
  "Poetry",
  "Storytelling",
  "Reading",
  "Book Clubs",
  "History",
  "Philosophy",
  "Psychology",
  "Languages",
  "Culture",
  "Architecture",
  "Museums",
  "Education",
  "Cooking",
  "Baking",
  "Nutrition",
  "Gardening",
  "Houseplants",
  "Home Improvement",
  "Interior Design",
  "Woodworking",
  "Pottery",
  "Sewing",
  "Travel",
  "Hiking",
  "Camping",
  "Cycling",
  "Running",
  "Swimming",
  "Climbing",
  "Water Sports",
  "Winter Sports",
  "Outdoor Adventures",
  "Fitness",
  "Yoga",
  "Meditation",
  "Mindfulness",
  "Sleep",
  "Self-Care",
  "Mental Wellbeing",
  "Healthy Habits",
  "Personal Growth",
  "Journaling",
  "Entrepreneurship",
  "Productivity",
  "Time Management",
  "Career Development",
  "Personal Finance",
  "Investing",
  "Marketing",
  "Public Speaking",
  "Leadership",
  "Networking",
  "Volunteering",
  "Community",
  "Friendship",
  "Family",
  "Parenting",
  "Pets",
  "Sustainability",
  "Recycling",
  "Board Games",
  "Puzzles",
] as const;

export type IdeaCategory = (typeof IDEA_CATEGORIES)[number];
